### ISSUE TITLE
html / xml code in tickets is not shown as text

### ISSUE THREAD

**Issue by rompic** [a-ono/redmine_ckeditor#158] opened 2015-03-30 15:39 UTC
Hi,
I have the problem that xml/html code is not shown as text. this is quite annoying when e.g. posting requests etc.

`<br>`
text
`<br>`

or
`<xml>`
test
`</xml>`

**Comment by rompic** [comment] 2015-03-30 17:04
Bzw. The text is shown currently in the preview

**Comment by rompic** [comment] 2015-04-06 07:03
tested with 1.0.20 on redmine 2.6.3

**Comment by a-ono** [comment] 2015-04-07 15:41
Confirmed but still not fixed it. refs 87032a2e5

**Comment by rompic** [comment] 2015-04-07 18:43
so the preview is actually not correct as well, as it has the same problem as https://github.com/a-ono/redmine_ckeditor/commit/87032a2e554951c1ced7319db49eac53e43ed848

**Comment by rompic** [comment] 2015-04-08 05:42
potential solution? http://komlenic.com/246/encoding-entities-to-work-with-ckeditor-3/

**Comment by rompic** [comment] 2015-04-08 06:53
as mentioned in the article:
if I escape the text to: &lt;xml&gt;11111&lt;/xml&gt; and save it works once
if I edit the text again it is turned to `<xml>11111</xml>` and after saving shown as 11111

the same is true if the show source code button is used repeatedly

**Comment by rompic** [comment] 2015-04-08 07:04
there's also a forceSimpleAmpersand: true setting which could be of interest

**Comment by a-ono** [comment] 2015-04-09 15:15
There seems to be no perfect solution.
The editor can be configured to encode, but it will cause issues like #132.

Please set below options if you want to do so.
https://github.com/a-ono/redmine_ckeditor#configuration-options
```
basicEntities: true
entities: true
```

**Comment by rompic** [comment] 2015-04-23 05:51
posted to stackoverflow to ask for help: http://stackoverflow.com/questions/29814698/encoding-of-entities-no-perfect-solution

**Comment by Reinmar** [comment] 2015-05-04 12:14
Please see http://stackoverflow.com/questions/29814698/encoding-of-entities-no-perfect-solution/30029866#30029866. **CKEditor's settings are totally correct by default and there's no need to touch anything**. If some content is displayed incorrectly after being saved in a database, it means that the backend is incorrectly processing it.

**Comment by rompic** [comment] 2015-05-10 08:15
@a-ono can you take another look into this problem? any pointers how I could support?

**Comment by a-ono** [comment] 2015-05-11 16:48
I wanted to enable Redmine's autolink because it was a little painful to insert link through CKEditor's dialog. And I decided to prevent CKEditor encoding because it was difficult to handle encoded values.

Although this is not a CKEditor's problem, there are some other problems in `config.basicEntities = false`.
For example, HTML entities are decoded each time at switching from source mode to visual mode.
I think it's not always necessary to store encoded values because it can be done at rendering without CKEditor.

---

Solutions will be like below.
* stop preventing CKEditor encoding
* give up autolink or implement it to handle encoded values

**Comment by rompic** [comment] 2015-07-17 20:16
any update on this issue?

**Comment by a-ono** [comment] 2015-11-03 14:56
Fixed in master branch.

**Closed by a-ono** 2015-11-03 14:56 UTC

**Comment by rompic** [comment] 2015-11-03 18:40
sounds good! thanks for the effort
